// Copyright 2018 Krister Joas <krister@joas.jp>

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

const std::vector<std::string> preamble =
{
  R"(# This file is automatically generated.

# Copyright 2018 Krister Joas <krister@joas.jp>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.)",

R"(rule COMPILE.cc
 command = c++ $incs ${-D} ${-I} ${-F} $ccflags -MMD -MF $out.d -c -o $out $in
 description = Compile $out
 depfile = $out.d

rule COMPILE.c
 command = cc $incs ${-D} ${-I} $cflags -MMD -MF $out.d  -c -o $out $in
 description = Compile $out
 depfile = $out.d

rule ARCHIVE
 command = ar cr $out $in
 description = Archive $out

rule LINK.cc
 command = c++ $ldflags $in ${-L} ${-l} ${-F} ${-framework} -o $out
 description = Link $out)"
};
